version: '3.4'

services:
  freshmarket-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: freshmarket.api
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001

  freshmarket-database:
    image: postgres:latest
    container_name: freshmarket.database
    environment:
      - POSTGRES_DB=freshmarket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432